# Generated by Django 2.2.6 on 2019-11-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torpedopage', '0005_torpedo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torpedo',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
