# Generated by Django 2.2.6 on 2019-11-17 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torpedopage', '0008_auto_20191117_1856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apunte',
        ),
    ]
