# Generated by Django 2.2.6 on 2019-11-17 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torpedopage', '0010_apunte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apunte',
        ),
    ]
