# Generated by Django 2.2.6 on 2019-11-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torpedopage', '0013_auto_20191128_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apunte',
            name='descripcion',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
