# Generated by Django 2.2.6 on 2019-11-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torpedopage', '0014_auto_20191128_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenLogo',
            fields=[
                ('nombre', models.CharField(help_text='Debe contener la palabra logo', max_length=200, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Descripción de la imagen logo', max_length=250)),
                ('imagen', models.ImageField(upload_to='media/galeria')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenSlider',
            fields=[
                ('nombre', models.CharField(help_text='Debe contener la palabra slider', max_length=200, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Descripción de la imagen', max_length=250)),
                ('imagen', models.ImageField(upload_to='media/galeria')),
            ],
        ),
        migrations.AlterField(
            model_name='apunte',
            name='descripcion',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
